# Generated by Django 4.1.5 on 2023-01-26 19:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
