# Generated by Django 4.1.5 on 2023-01-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_title', models.CharField(max_length=200)),
                ('pos_field', models.CharField(max_length=200)),
                ('pos_desc', models.CharField(max_length=5000)),
                ('pos_host', models.CharField(max_length=200)),
                ('pos_country', models.CharField(max_length=200)),
                ('pos_pub_date', models.DateTimeField(verbose_name='date published')),
                ('pos_exp_date', models.DateTimeField(verbose_name='date expiring')),
                ('pos_link', models.URLField(default='https://www.ice.csic.es/')),
            ],
        ),
    ]
