# Generated by Django 4.1.5 on 2023-01-26 09:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_alter_position_pos_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='pos_country',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='position',
            name='pos_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, null=True, size=None),
        ),
    ]
